spring.application.name=backend-erp-clinica

server.port=8085

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.jackson.time-zone=America/Lima
spring.jackson.locale=es_PE

spring.datasource.url=jdbc:postgresql://localhost:5432/erp_clinica_principal
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration